"""updated relationships

Revision ID: 35feadb564b5
Revises: 6d1022cca52a
Create Date: 2025-04-13 07:01:26.794718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35feadb564b5'
down_revision = '6d1022cca52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_connections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_connections',
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['tags.id'], name='tag_connections_source_id_fkey'),
    sa.ForeignKeyConstraint(['target_id'], ['tags.id'], name='tag_connections_target_id_fkey'),
    sa.PrimaryKeyConstraint('source_id', 'target_id', name='tag_connections_pkey')
    )
    # ### end Alembic commands ###
